name: japp
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  hooks_riverpod: ^1.0.3
  file_picker: ^4.3.3
  flutter_hooks: ^0.18.2
  dio_cache_interceptor: ^3.2.2
  getwidget: ^2.0.4
  dartz: ^0.10.1
  flutter_typeahead: ^3.2.4
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  intl: ^0.17.0
  fluro: ^2.0.3
  json_annotation: ^4.4.0
  package_info_plus: ^1.3.0  
  email_validator: ^2.0.1  
  smooth_page_indicator: ^1.0.0+2
  lottie: ^1.2.1
  google_fonts: ^2.3.1
  chips_choice: ^2.0.1
  universal_platform: ^1.0.0+1
  easy_logger: ^0.0.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/Circular-Std-Book.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
